export const INVALID_TOKEN_ERROR = "INVALID_TOKEN_ERROR";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR";
export const UNSUPPORTED_FILE_TYPE_ERROR = "UNSUPPORTED_FILE_TYPE_ERROR";
