"""
## Authentication and Authorization directive
Any field with no @auth directive is public by default
Calling the @auth directive without any rules means the user must be authenticated
Calling the @auth(rules: [{ ... }]) with rules means the user must be authorized according to the set rules
**Authorization rules operate on the deny-by-default principle**. Meaning that if an authorization rule is not specifically configured, it is denied.
"""
directive @auth(rules: [AuthRule!]) on FIELD_DEFINITION | OBJECT

enum AuthStrategy {
  """
  To restrict a record's access to a specific user, use the `owner` strategy.
  When `owner` authorization is configured, only the record's `owner` and admins are allowed the specified operations.
  """
  owner
}

input AuthRule {
  allow: AuthStrategy!
  identityClaim: String = "ownerId"
}
