scalar LocalDateTime

type Meeting {
  id: ID!
  title: String!
  timezone: String!
  from: LocalDateTime!
  to: LocalDateTime!
  description: String
  isOwner: Boolean!
  owner: User!
  teams: [Team]!
  createdAt: DateTime!
  updatedAt: DateTime
}

input CreateMeetingInput {
  title: NonEmptyString!
  timezone: NonEmptyString!
  from: LocalDateTime!
  to: LocalDateTime!
  description: NonEmptyString
  teamIds: [ID]
}

input UpdateMeetingInput {
  id: ID!
  title: NonEmptyString!
  timezone: NonEmptyString!
  from: LocalDateTime!
  to: LocalDateTime!
  description: NonEmptyString
  teamIds: [ID]
}

type Mutation {
  createMeeting(input: CreateMeetingInput!): Meeting! @auth
  updateMeeting(input: UpdateMeetingInput!): Meeting! @auth
  deleteMeeting(id: ID!, reason: NonEmptyString): Meeting! @auth
}

type Query {
  getMeetingById(id: ID!): Meeting! @auth
  getMeetings: MeetingConnection! @auth
}

type MeetingConnection {
  meetings: [Meeting]!
  cursor: ID
}
