type Profile {
  id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  photo: URL
  countryCode: CountryCode!
  timezone: TimeZone!
  locale: Locale
  teams: [Team]!
  createdAt: DateTime!
  updatedAt: DateTime
}

type Query {
  getProfileById(id: ID!): Profile!
}

type Mutation {
  updateCurrentUserFullName(
    firstName: NonEmptyString!
    lastName: NonEmptyString!
  ): Profile!
  updateCurrentUserTimeZone(timezone: TimeZone!): Profile!
  updateCurrentUserCountry(countryCode: CountryCode!): Profile!
}
