type Profile {
  id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  picture: URL
  countryCode: CountryCode
  timezone: TimeZone
  locale: Locale
  teams: [TeamMember]! @auth(rules: [{ allow: owner }])
  createdTeams: [Team]! @auth(rules: [{ allow: owner }])
  createdAt: DateTime!
  updatedAt: DateTime
  owner: User @auth(rules: [{ allow: owner }])
}

type Query {
  getProfileById(id: ID!): Profile! @auth
}

type Mutation {
  updateCurrentUserFullName(
    firstName: NonEmptyString!
    lastName: NonEmptyString!
  ): Profile! @auth
  updateCurrentUserTimeZone(timezone: TimeZone!): Profile! @auth
  updateCurrentUserCountry(countryCode: CountryCode!): Profile! @auth
  updateCurrentUserLocale(locale: Locale!): Profile! @auth
}
