type Team {
  id: ID!
  name: String!
  photo: URL
  inviteCode: ID
  teammates: [TeamMember]!
  createdAt: DateTime!
  updatedAt: DateTime
}

type TeamMember {
  id: ID!
  team: Team!
  profile: Profile!
  joinedAt: DateTime!
}

type Query {
  getTeamById(id: ID!): Team!
}

type Mutation {
  createTeam(input: CreateTeamInput!): Team!
  updateTeam(input: UpdateTeamInput!): Team!
  deleteTeam(id: ID!): Team!
  archiveTeam(id: ID!): Team!
  joinTeam(inviteCode: ID!): TeamMember!
  leaveTeam(teamId: ID!): TeamMember!
  removeTeammates(memberIds: [ID!]!): [TeamMember!]!
}

input CreateTeamInput {
  name: NonEmptyString!
}

input UpdateTeamInput {
  id: ID!
  name: NonEmptyString!
}
