type TimezoneData {
  name: TimeZone!
  alternativeName: String
  group: [TimeZone]
  continentCode: String!
  continentName: String!
  countryName: String!
  countryCode: CountryCode
  countryFlag(height: PositiveInt = 20): URL!
  mainCities: [String]
  rawOffsetInMinutes: Int!
  abbreviation: String!
  rawFormat: String!
  currentTimeOffsetInMinutes: Int!
  currentTimeFormat: String!

  sunrise: DateTime
  sunset: DateTime
  teammates: [TeamMember]!
}

type Query {
  timezones: [TimezoneData!]! @auth
}
