type User {
  id: ID!
  email: EmailAddress! @auth(rules: [{ allow: owner, identityClaim: "id" }])
  emailVerified: Boolean!
  profile: Profile
  createdAt: DateTime!
  updatedAt: DateTime
}

type Query {
  me: User! @auth
}

type AuthPayload {
  token: JWT
}

type Mutation {
  loginWithGoogle(idToken: JWT!): AuthPayload!
}
