type User {
  id: ID!
  email: EmailAddress!
  profile: Profile
  createdAt: DateTime!
  updatedAt: DateTime
}

type Query {
  me: User!
}

type AuthPayload {
  accessToken: JWT
}

type Mutation {
  loginWithSocialProvider(input: SocialLoginInput!): AuthPayload!
}

enum SocialProvider {
  GOOGLE
}

input SocialLoginInput {
  token: NonEmptyString!
  provider: SocialProvider!
}
